export const FETCH_QUESTIONS = "FETCH_QUESTIONS";
export const ADD_QUESTION = "ADD_QUESTION";

export const FETCH_SUCCEEDED = "FETCH_SUCCEEDED";
export const FETCH_FAILED = "FETCH_FAILED";
export const ADD_QUESTION_SUCCEEDED = "ADD_QUESTION_SUCCEEDED";


export const FETCH_ADVERT = "FETCH_ADVERT";
export const FETCH_ADVERT_SUCCEEDED = "FETCH_ADVERT_SUCCEEDED";

export const FETCH_PLAYLISTS = "FETCH_PLAYLISTS";
export const FETCH_PLAYLISTS_SUCCEEDED = "FETCH_PLAYLISTS_SUCCEEDED";