const SONGLISTSCREEN = "SONGLISTSCREEN";
const HOMESCREEN = "HOMESCREEN";
const GROUPSCREEN = "GROUPSCREEN";
const AUDIOPLAYERSCREEN ="AUDIOPLAYERSCREEN";
const SEARCHSCREEN ="SEARCHSCREEN";
export  {
    SONGLISTSCREEN,
    HOMESCREEN,
    GROUPSCREEN,
    AUDIOPLAYERSCREEN,
    SEARCHSCREEN
};

export const ApiServer = "https://musicappservice.herokuapp.com";

export const FETCH_QUESTIONS = "FETCH_QUESTIONS";
export const ADD_QUESTION = "ADD_QUESTION";

export const FETCH_SUCCEEDED = "FETCH_SUCCEEDED";
export const FETCH_FAILED = "FETCH_FAILED";
export const ADD_QUESTION_SUCCEEDED = "ADD_QUESTION_SUCCEEDED";


export const FETCH_ADVERT = "FETCH_ADVERT";
export const FETCH_ADVERT_SUCCEEDED = "FETCH_ADVERT_SUCCEEDED";

export const FETCH_PLAYLISTS = "FETCH_PLAYLISTS";
export const FETCH_PLAYLISTS_SUCCEEDED = "FETCH_PLAYLISTS_SUCCEEDED";

export const FETCH_ALL_PLAYLISTS = "FETCH_ALL_PLAYLISTS";
export const FETCH_ALL_PLAYLISTS_SUCCEEDED = "FETCH_ALL_PLAYLISTS_SUCCEEDED";

export const FETCH_TOPICGENRES = "FETCH_TOPICGENRES";
export const FETCH_TOPICGENRES_SUCCEEDED = "FETCH_TOPICGENRES_SUCCEEDED";

export const FETCH_ALBUMS = "FETCH_ALBUMS";
export const FETCH_ALBUMS_SUCCEEDED = "FETCH_ALBUMS_SUCCEEDED";

export const FETCH_ALL_ALBUMS = "FETCH_ALL_ALBUMS";
export const FETCH_ALL_ALBUMS_SUCCEEDED = "FETCH_ALL_ALBUMS_SUCCEEDED";

export const FETCH_ALL_GENRE = "FETCH_ALL_GENRE";
export const FETCH_ALL_GENRE_SUCCEEDED = "FETCH_ALL_GENRE_SUCCEEDED";

export const RESET_SONG_LIST = "RESET_SONG_LIST";
export const RESET_GROUP = "RESET_GROUP";

export const FETCH_FAVOURITESONGS = "FETCH_FAVOURITESONGS";
export const FETCH_FAVOURITESONGS_SUCCEEDED = "FETCH_FAVOURITESONGS_SUCCEEDED";


export const FETCH_ADVERT_SONGS = "FETCH_ADVERT_SONGS";
export const FETCH_ADVERT_SONGS_SUCCEEDED = "FETCH_ADVERT_SONGS_SUCCEEDED";

export const FETCH_PLAYLIST_SONGS = "FETCH_PLAYLIST_SONGS";
export const FETCH_PLAYLIST_SONGS_SUCCEEDED = "FETCH_PLAYLIST_SONGS_SUCCEEDED";


export const FETCH_GENRE_SONGS = "FETCH_GENRE_SONGS";
export const FETCH_GENRE_SONGS_SUCCEEDED = "FETCH_GENRE_SONGS_SUCCEEDED";


export const FETCH_ALBUM_SONGS = "FETCH_ALBUM_SONGS";
export const FETCH_ALBUM_SONGS_SUCCEEDED = "FETCH_ALBUM_SONGS_SUCCEEDED";


export const SEARCH_SONGS = "SEARCH_SONGS";
export const SEARCH_SONGS_SUCCEEDED = "SEARCH_SONGS_SUCCEEDED";